#:kivy 1.10.0

<ChineseLabel@Label>:
    font_size: 36
    text_size: self.size
    color: 0, 0, 0, 1
    halign: 'center'
    valign: 'center'
    font_name: 'data/HuaKangTiFan-CuTi-1.otf'
<ChineseButton@Button>:
    background_normal: 'data/images/white.png'
    font_size: 28
    text_size: self.size
    color: 0, 0, 0, 1
    halign: 'center'
    valign: 'center'
    font_name: 'data/HuaKangTiFan-CuTi-1.otf'