#:kivy 1.10.0

<ChineseLabel@Label>:
    font_size: 32
    text_size: self.size
    color: 0, 0, 0, 1
    halign: 'center'
    valign: 'center'
    font_name: 'data/DroidSansFallback.ttf'
<ChineseButton@Button>:
    background_normal: 'data/images/white.png'
    font_size: 20
    text_size: self.size
    color: 0, 0, 0, 1
    halign: 'center'
    valign: 'center'
    font_name: 'data/DroidSansFallback.ttf'