#:kivy 1.10.0

<ChineseLabel@Label>:
    font_size: 32
    text_size: self.size
    halign: 'center'
    valign: 'center'
    font_name: 'data/DroidSansFallback.ttf'
<ChineseButton@Button>:
    ##background_normal: 'data/images/normal.png'
    ##background_down: 'data/images/down.png'
    font_size: 20
    text_size: self.size
    halign: 'center'
    valign: 'center'
    font_name: 'data/DroidSansFallback.ttf'