#:kivy 1.10.0

<CountDownLabel>:

<LocationScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'data/images/map_resized.png'

<DualScreen>:

<ChanceCardBG>:
    ChineseButton:
        background_normal: 'data/images/chance_bg.png'
        on_press:
            root.manager.transition.direction = 'up'
            root.manager.current = 'chance'