#:kivy 1.10.0
#:import kivy kivy
#:import win kivy.core.window
#:import Factory kivy.factory.Factory

#:include kv/chinese.kv
#:include kv/dummy.kv
#:include kv/question.kv

## the first charator of custom class must be upper class
<PlayerChess>:
    canvas:
        Color:
            rgba: self.color
        Rectangle:
            pos: (root.width * self.rel_pos['x'], root.height * self.rel_pos['y'])
            size: (root.width / 40, root.width / 40)
            source: self.source

<BlockStatus>:
    canvas:
        Color:
            rgba: self.color
        Rectangle:
            pos: (root.width * self.rel_pos['x'], root.height * self.rel_pos['y'])
            size: (root.width / 15, root.width / 15)
            source: root.source_img

<MapScreen>:
    ## pos_hint is from bottom left corner           
    ## size_hint is (width, height)
    FloatLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/images/map_resized.png'
        BoxLayout:
            padding: 10
            spacing: 10
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 0.5
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.3, 0.5)
            pos_hint: {'x': 0.5, 'y': 0.25}
            orientation: 'vertical'
            ChineseButton:
                background_color: .5, .5, .5, 1
                color: 1, 1, 1, 1
                text: '確認分數 or 結束遊戲'
                on_release:
                    root.manager.current = 'end'
            ChineseButton:
                background_color: .5, .5, .5, 1
                color: 1, 1, 1, 1
                text: '擲骰子!'
                on_release:
                    root.rollDice()
            ChineseLabel:
                text: root.diceSum
                font_size: 24
                color: 0, 0, 0, 1
    PlayerChess:
        id: player_chess_0
    PlayerChess:
        id: player_chess_1
    PlayerChess:
        id: player_chess_2
    PlayerChess:
        id: player_chess_3
    PlayerChess:
        id: player_chess_4
    PlayerChess:
        id: player_chess_5

<CorrectAnswerScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.988, 0.988, 0.988, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            text: str('題目: '+root.question)
            size_hint: (1, .3)
            text_size: self.width, None
        ChineseLabel:
            canvas.before:
                Color:
                    rgba: 0.392, 0.850, 0.776, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            text: str('挑戰成功!\n'+root.description)
            size_hint: (1, .55)
            text_size: self.width, None
        ChineseButton:
            text: '確認結果'
            background_color: 1, 0.901, 0.6, 1
            size_hint: (1, .15)
            on_release:
                root.callback()

<WrongAnswerScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.988, 0.988, 0.988, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            text: str('題目: '+root.question)
            size_hint: (1, .3)
            text_size: self.width, None
        ChineseLabel:
            canvas.before:
                Color:
                    rgba: 1, 0.811, 0.811, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            text: str('挑戰失敗!\n正確答案是: '+root.correct_answer+'\n'+root.description)
            size_hint: (1, .55)
            text_size: self.width, None
        ChineseButton:
            text: '回到地圖'
            background_color: 1, 0.901, 0.6, 1
            size_hint: (1, .15)
            on_release:
                root.callback()

<TitleScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.392, 0.850, 0.776, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            size_hint: 1, 0.7
            font_size: 96
            font_name: 'data/MGentleHK-Light.otf'
            color: 1, 1, 1, 1
            text: '臺大大富翁'
        BoxLayout:
            size_hint: 1, 0.3
            orientation: 'horizontal'
            padding: 50
            spacing: 30
            ChineseButton:
                background_color: 1, 0.937, 0.741, 1
                text: '規則說明'
                color: 1, 0.607, 0.607, 1
                font_size: 40
                font_name: 'data/MBitmapRoundHK-Light.otf'
                on_release:
                    root.gotoInfo()
            ChineseButton:
                background_color: 1, 0.607, 0.607, 1
                text: '開始遊戲'
                color: 1, 1, 1, 1
                font_size: 40
                font_name: 'data/MBitmapRoundHK-Light.otf'
                on_release:
                    root.startGame()

<InfoScreen>:
    BoxLayout:
        orientation: 'horizontal'
        padding: 30
        spacing: 10
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        BoxLayout:
            orientation: 'vertical'
            padding: 10
            spacing: 10
            size_hint: (.32, 1)
            ChineseLabel:
                ## pink
                size_hint: (1, .4)
                canvas.before:
                    Color:
                        rgba: 1, 0.607, 0.607, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                font_size: 28
                halign: 'left'
                text: '勝利條件：\n遊戲結束時，佔領景點積分最高的小隊獲勝！'
            ChineseLabel:
                size_hint: (1, .4)
                canvas.before:
                    Color:
                        rgba: 1, 0.937, 0.741, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                font_size: 28
                halign: 'left'
                text: '小提示：\n走到起點時，獲得一次隨機景點答題機會><'
            BoxLayout:
                size_hint: (1, .2)
                orientation: 'horizontal'
                spacing: 10
                ChineseButton:
                    ## light blue
                    background_color: 0.3, 0.9, 0.95, 1
                    text: '回上一頁'
                    on_release:
                        root.goback()
                ChineseButton:
                    ## light blue
                    background_color: 0.3, 0.9, 0.95, 1
                    text: '開始遊戲'
                    on_release:
                        root.startGame()
        ChineseLabel:
            size_hint: (.68, 1)
            font_size: 28
            halign: 'left'
            text: '遊戲規則\n\n1,小隊輪流擲骰子並依點數前進\n2,抵達景點後，在時限內答對題目則佔領該景點\n3,其他隊伍抵達該景點時，進行決鬥！挑戰者勝利則奪取該景點，原占領者勝利則獲得衛冕該景點\n4,另一種衛冕的方式為：原隊重抵該景點並答對題目\n5,兩次衛冕該景點則可永久佔領\n6,佔領景點積分：佔領1分、衛冕2分、永久佔領3分'

<ResultScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 50
        canvas.before:
            Color:
                rgba: 0.988, 0.988, 0.988, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            size_hint:  1, .3
            text: '第' + str(root.player+1) + '組'
        ChineseLabel:
            size_hint:  1, .4
            text: root.action + root.location
        BoxLayout:
            orientation: 'horizontal'
            size_hint:  1, .3
            padding: 30
            spacing: 30
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: 1, 0.901, 0.6, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '目前總分: ' + str(root.score)
            ChineseButton:
                text: '繼續'
                background_color: 0.392, 0.850, 0.776, 1
                on_release:
                    root.callback()

<EndScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 30
        canvas.before:
            Color:
                rgba: 0.988, 0.988, 0.988, 1
            Rectangle:
                pos: self.pos
                size: self.size
        GridLayout:
            size_hint: (1, .8)
            cols: 3
            spacing: 5
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[0]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第1組:\n' + str(root.score1) + '分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[1]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第2組:\n'+ str(root.score2) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[2]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第3組:\n'+ str(root.score3) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[3]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第4組:\n'+ str(root.score4) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[4]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第5組:\n'+ str(root.score5) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[5]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第6組:\n'+ str(root.score6) +'分'
        ChineseButton:
            size_hint: (1, .2)
            background_color: 0.760, 0.760, 0.760, 1
            text: '回地圖繼續'
            on_release:
                root.callback()

<ChanceScreen>:
    BoxLayout:
        id: main_box
        orientation: 'vertical'
        spacing: 30
        padding: 50
        canvas.before:
            Color:
                rgba: 0.988, 0.988, 0.988, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            size_hint: (1, .2)
            text: '第'+str(root.currentPlayer+1)+'組獲得機會卡:'
        ChineseLabel:
            size_hint: (1, .65)
            text: root.description
        ChineseButton:
            id: chance_back_btn
            size_hint: (1, .15)
            text: root.btn_text
            background_color: 1, 0.901, 0.6, 1
            on_release:
                root.callback()
    
<ChanceChooseTeamScreen>:
    BoxLayout:
        id: main_box
        orientation: 'vertical'
        spacing: 30
        padding: 50
        canvas.before:
            Color:
                rgba: 0.988, 0.988, 0.988, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            size_hint: (1, .2)
            text: '第'+str(root.currentPlayer+1)+'組的機會卡:'
        ChineseLabel:
            size_hint: (1, .65)
            text: root.description + '\n請選擇組別'
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, .15)
            spacing: 5
            ChineseButton:
                text: '第1組'
                background_color: 1, 0.901, 0.6, 1
                on_release: root.choose_team(0)
            ChineseButton:
                text: '第2組'
                background_color: 1, 0.901, 0.6, 1
                on_release: root.choose_team(1)
            ChineseButton:
                text: '第3組'
                background_color: 1, 0.901, 0.6, 1
                on_release: root.choose_team(2)
            ChineseButton:
                text: '第4組'
                background_color: 1, 0.901, 0.6, 1
                on_release: root.choose_team(3)
            ChineseButton:
                text: '第5組'
                background_color: 1, 0.901, 0.6, 1
                on_release: root.choose_team(4)
            ChineseButton:
                text: '第6組'
                background_color: 1, 0.901, 0.6, 1
                on_release: root.choose_team(5)