#:kivy 1.10.0
#:import kivy kivy
#:import win kivy.core.window
#:import Factory kivy.factory.Factory

#:include kv/chinese.kv
#:include kv/dummy.kv
#:include kv/question.kv

## the first charator of custom class must be upper class

<MapScreen>:
    ## pos_hint is from bottom left corner           
    ## size_hint is (width, height)
    FloatLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/images/map_resized.png'
        BoxLayout:
            padding: 10
            spacing: 10
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 0.5
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.3, 0.5)
            pos_hint: {'x': 0.5, 'y': 0.25}
            orientation: 'vertical'
            ChineseButton:
                text: '確認分數 or 結束遊戲'
                on_release:
                    root.manager.current = 'end'
            ChineseButton:
                text: '擲骰子!'
                on_release:
                    root.rollDice()
            ChineseLabel:
                text: root.diceSum
                font_size: 24
                color: 0, 0, 0, 1

<CorrectAnswerScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 50
        spacing: 10
        canvas:
            Color:
                rgba: 0, 0, 0, 0.3
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            canvas.before:
                Color:
                    ## green background
                    rgba: 0.15, 0.9, 0.1, 0.5
                Rectangle:
                    pos: self.pos
                    size: self.size
            text: str('挑戰成功!\n\n'+root.description)
            size_hint: (1, .8)
            text_size: self.width, None
        ChineseButton:
            text: '確認結果'
            size_hint: (1, .2)
            on_release:
                root.callback()

<WrongAnswerScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 50
        spacing: 10
        canvas:
            Color:
                rgba: 0, 0, 0, 0.3
            Rectangle:
                pos: self.pos
                size: self.size
        ChineseLabel:
            canvas.before:
                Color:
                    ## red background
                    rgba: 0.9, 0.1, 0.125, 0.5
                Rectangle:
                    pos: self.pos
                    size: self.size
            text: str('挑戰失敗!\n正確答案是: '+root.correct_answer+'\n\n'+root.description)
            size_hint: (1, .8)
            text_size: self.width, None
        ChineseButton:
            text: '回到地圖'
            size_hint: (1, .2)
            on_release:
                root.callback()

<TitleScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 10
        ChineseLabel:
            font_size: 72
            text: '台大大富翁'
        BoxLayout:
            orientation: 'horizontal'
            padding: 50
            spacing: 30
            ChineseButton:
                text: '規則說明'
                on_release:
                    root.gotoInfo()
            ChineseButton:
                text: '開始遊戲'
                on_release:
                    root.startGame()

<InfoScreen>:
    BoxLayout:
        orientation: 'horizontal'
        padding: 30
        spacing: 10
        BoxLayout:
            orientation: 'vertical'
            padding: 10
            spacing: 10
            ChineseLabel:
                ## pink
                canvas.before:
                    Color:
                        rgba: 0.9, 0.1, 0.9, 0.7
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '勝利條件'
            ChineseLabel:
                ## orange
                canvas.before:
                    Color:
                        rgba: 0.95, 0.6, 0.3, 0.7
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '小提示'
            BoxLayout:
                orientation: 'horizontal'
                spacing: 10
                ChineseButton:
                    ## light blue
                    background_color: 0.3, 0.9, 0.95, 1
                    text: '回上一頁'
                    on_release:
                        root.goback()
                ChineseButton:
                    ## light blue
                    background_color: 0.3, 0.9, 0.95, 1
                    text: '開始遊戲'
                    on_release:
                        root.startGame()
        ChineseLabel:
            text: '遊戲規則'

<ResultScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 50
        ChineseLabel:
            text: '恭喜第' + str(root.player+1) + '組'
        ChineseLabel:
            text: root.action + root.location
        BoxLayout:
            orientation: 'horizontal'
            padding: 30
            spacing: 10
            ChineseLabel:
                text: '目前總分: ' + str(root.score)
            ChineseButton:
                text: '繼續'
                on_release:
                    root.callback()

<EndScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 30
        GridLayout:
            size_hint: (1, .8)
            cols: 3
            spacing: 5
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[0]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第1組:\n' + str(root.score1) + '分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[1]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第2組:\n'+ str(root.score2) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[2]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第3組:\n'+ str(root.score3) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[3]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第4組:\n'+ str(root.score4) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[4]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第5組:\n'+ str(root.score5) +'分'
            ChineseLabel:
                canvas.before:
                    Color:
                        rgba: root.background_color[5]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: '第6組:\n'+ str(root.score6) +'分'
        ChineseButton:
            size_hint: (1, .2)
            text: '回地圖繼續'
            on_release:
                root.callback()